version: '3'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sportmarket
      POSTGRES_USER: sportmarket
      POSTGRES_PASSWORD: pookrchdio123
    ports:
      - "32793:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
